#Makefile for simulations
# Not used for building simulate.py
# Used for building/removing results

BASEDIR = /home/sam/Documents/progcomp2012/
RESULTSDIR = /home/sam/Documents/progcomp2012/results
LOGDIR = /home/sam/Documents/progcomp2012/log
AGENTSDIR = /home/sam/Documents/progcomp2012/samples
MANAGER = /home/sam/Documents/progcomp2012/manager/stratego



clean:
	rm -r -f $(RESULTSDIR)
	rm -r -f $(LOGDIR)
