#Makefile for simulations
# Not used for building simulate.py
# Used for building/removing results

BASEDIR = /../../
RESULTSDIR = /../../web/results
LOGDIR = /../../web/log
AGENTSDIR = /../../agents
MANAGER = /../../judge/manager/stratego



clean:
	rm -r -f $(RESULTSDIR)
	rm -r -f $(LOGDIR)

