#Makefile for simulations
# Not used for building simulate.py
# Used for building/removing results

BASEDIR = /home/sam/Documents/progcomp2012/progcomp
RESULTSDIR = /home/sam/Documents/progcomp2012/progcomp/web/results
LOGDIR = /home/sam/Documents/progcomp2012/progcomp/web/log
AGENTSDIR = /home/sam/Documents/progcomp2012/progcomp/agents
MANAGER = /home/sam/Documents/progcomp2012/progcomp/judge/manager/stratego



clean:
	rm -r -f $(RESULTSDIR)
	rm -r -f $(LOGDIR)

